---
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: nestjs-server
    metrics_path: /v1/metrics
    scheme: https
    static_configs:
      - targets: [api.blazechat.se]  # Replace with your NestJS server IP and port
